### ISSUE TITLE
Person affiliation lacks context of organisation

### ISSUE THREAD

**Issue by danielgrant** [JiscRDSS/rdss-canonical-data-model#111]
Crosspost from this issue: https://github.com/JiscRDSS/rdss-message-api-docs/issues/37

`personAffiliation` is an array of enums representing types of affiliation

`personOrganisation` is an array of Organisation objects

It appears, or at least a cursory inspection seems to indicate, that there can be a case where a `person` has multiple organisations with different `affiliation types`, but isn't clear we can represent this.

**Comment by DomFripp** [comment]
Legacy issue fixed in CDM 3.0.0 with removal of UKAMF specific metadata fields.
