### ISSUE TITLE
Publication properties: publicationLanguage

### ISSUE THREAD

**Issue by DomFripp** [JiscRDSS/rdss-canonical-data-model#70]
Can it default to English?

[Cam]

**Comment by DomFripp** [comment]
Hi @alanmackenzie , I guess this can be done but wanted to check with you.

**Comment by alanmackenzie** [comment]
Hi @DomFripp,

Yes this is no problem. In terms of capturing this UML has a property of attributes called "Default value". For more compelx cases that involve business logic you can simply use a note.

More detail here: https://msdn.microsoft.com/en-us/library/dd323861.aspx

**Comment by DomFripp** [comment]
![image](https://cloud.githubusercontent.com/assets/19859318/22975241/ebfd4522-f37d-11e6-8719-1f041cccd04d.png)
