### ISSUE TITLE
add storage location properties to File entity

### ISSUE THREAD

**Issue by peterVG** [JiscRDSS/rdss-canonical-data-model#97]
During RDSS-Archivematica Alpha MVP Sprint 2, we encountered the requirement to retrieve all the Files that are included for a given Dataset from their JiscRDSS cloud storage location (S3). These Files are listed in the Metadata Read message payload that RDSS-Archivematica receives to trigger a register-preservation-message event for that Dataset. However, the current version of the RDSS Canonical Data Model (CDM) does not have the necessary properties specified to use for file storage location values.  

See recommended changes on my fork here. https://github.com/peterVG/rdss-canonical-data-model/commit/118296f5492479dca65c90ae7eccb368234bc027 Can do PR if there's agreement.

**Comment by DomFripp** [comment]
Looks good to me, @peterVG  - please set up a pull request. 

I'll need to raise a separate PR for the change to the UML.

**Comment by peterVG** [comment]
done, cheers.
