### ISSUE TITLE
add Checksum entity to /properties folder

### ISSUE THREAD

**Issue by peterVG** [JiscRDSS/rdss-canonical-data-model#98]
This entity is specified on the logical model diagram but it is not listed amongst the entities in the JiscRDSS/rddss-canonical-data-model/properties directory.

During RDSS-Archivematica Alpha MVP Sprint 2, we encountered the standard digital preservation requirement to verify a chain of custody for Files once they enter the Preservation System domain. In order to support this requirement RDSS-Archivematica needs to read and verify checksum values for all the Files in a Dataset when they are moved to and from their JiscRDSS cloud storage location (S3). 

These Files are listed in the Metadata Read message payload that RDSS-Archivematica receives to trigger a register-preservation-message event for that Dataset. However, the current (textual) version of the RDSS Canonical Data Model (CDM) does not have the necessary properties specified to use for checksum values (nor are these present for the Metadata Create payload specifications in the current rdss-messaging-api-docs).

**Comment by DomFripp** [comment]
Good spot. I hold my hands up and say this was during a rapid and extensive data model UML change when the documentation got left behind. 

Do you have a suggestion for the documentation to go with this in properties? I can dive into it if not.

**Comment by DomFripp** [comment]
Checksum field description now in properties document.
